# Generated by Django 3.1.4 on 2020-12-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoofi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
