# Generated by Django 3.1.4 on 2020-12-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoofi', '0004_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('School', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('Confirmpassword', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Newuser',
        ),
    ]
