# Generated by Django 3.1.4 on 2020-12-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoofi', '0005_auto_20201223_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
