# Generated by Django 3.1.4 on 2020-12-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoofi', '0006_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Rollno',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
